import { chromium } from "@playwright/test";
import { mkdir, writeFile } from "node:fs/promises";
import os from "node:os";

const root = new URL("../", import.meta.url).pathname;
const output = `${root}docs/evidence`;
await mkdir(output, { recursive: true });
const requestedBackend = process.env.AUDIT_BACKEND || "webgl";
const suffix =
  process.env.AUDIT_SUFFIX || (requestedBackend === "webgl" ? "" : "-auto");
const baseURL = process.env.AUDIT_URL || "http://127.0.0.1:4175";
const mode = process.env.AUDIT_MODE || "baseline";
const checkpoint = mode === "checkpoint";
const observations = [],
  errors = [],
  consoleMessages = [];
const browser = await chromium.launch({
  executablePath:
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  headless: true,
  args: ["--use-angle=metal", "--enable-webgl", "--ignore-gpu-blocklist"],
});
const context = await browser.newContext({
  viewport: { width: 1920, height: 1080 },
  deviceScaleFactor: 1,
});
const page = await context.newPage();
// Prevent Vite HMR from replacing the page while another agent edits source.
// Core single-player gameplay does not use WebSockets.
await page.routeWebSocket("**", (socket) => socket.close());
page.on("pageerror", (error) =>
  errors.push({ time: Date.now(), message: error.message, stack: error.stack }),
);
page.on("console", (message) => {
  if (["error", "warning"].includes(message.type()))
    consoleMessages.push({
      type: message.type(),
      text: message.text(),
      location: message.location(),
    });
});
page.on("requestfailed", (request) =>
  errors.push({ request: request.url(), failure: request.failure() }),
);
page.on("response", (response) => {
  if (response.status() >= 400)
    consoleMessages.push({
      type: "http",
      status: response.status(),
      url: response.url(),
    });
});
const brief = (snapshot) => {
  const { frameTimes, ...rest } = snapshot;
  return { ...rest, frameSamples: frameTimes.length };
};
const snapshot = async (label) => {
  const value = await page.evaluate(() => window.__leonida.snapshot());
  observations.push({
    label,
    wallTime: new Date().toISOString(),
    ...brief(value),
  });
  console.log(JSON.stringify({ label, ...brief(value) }));
  return value;
};
const capture = async (label) =>
  page.screenshot({ path: `${output}/audit-${label}${suffix}.png` });
// Inspect only the save generated by normal UI actions; never alter browser storage.
const readUISave = async (label) => {
  const storage = await context.storageState();
  const entry = storage.origins
    .flatMap((origin) => origin.localStorage)
    .find((item) => item.name === "leonida.sandbox.v1");
  if (!entry) throw new Error("Normal UI save did not create sandbox data");
  const value = JSON.parse(entry.value);
  observations.push({ label, value });
  return value;
};
const assertObservation = (label, passed, detail) => {
  observations.push({ label, passed, detail });
  if (!passed) throw new Error(`${label}: ${JSON.stringify(detail)}`);
};
const hold = async (keys, ms) => {
  for (const key of keys) await page.keyboard.down(key);
  await page.waitForTimeout(ms);
  for (const key of [...keys].reverse()) await page.keyboard.up(key);
};
const openCreative = async () => {
  await page.keyboard.press("F2");
  await page.locator("#spawn-kind").waitFor({ state: "visible" });
};
const closePanel = async () => {
  await page.locator('#panel [data-action="close"]').click();
  await page.locator("#panel").waitFor({ state: "hidden" });
};
const observeOutcome = async (label, durationMs) => {
  const stop = Date.now() + durationMs;
  let nextSnapshot = 0,
    lastOutcome = "";
  while (Date.now() < stop) {
    const outcome = (await page.locator("#outcome").isVisible())
      ? await page.locator("#outcome").innerText()
      : "";
    if (outcome !== lastOutcome) {
      observations.push({
        label: `${label}-outcome`,
        value: outcome,
        cash: await page.locator("#money").innerText(),
        at: new Date().toISOString(),
      });
      lastOutcome = outcome;
      if (outcome) await capture(`${label}-${outcome.toLowerCase()}`);
    }
    if (Date.now() > nextSnapshot) {
      await snapshot(
        `${label}-${Math.round((durationMs - (stop - Date.now())) / 1000)}s`,
      );
      nextSnapshot = Date.now() + 5000;
    }
    await page.waitForTimeout(300);
  }
  observations.push({
    label: `${label}-cash`,
    value: await page.locator("#money").innerText(),
  });
  await snapshot(`${label}-end`);
  await capture(`${label}-end`);
};

try {
  await page.goto(
    `${baseURL}/${requestedBackend === "webgl" ? "?backend=webgl" : ""}`,
    { waitUntil: "domcontentloaded", timeout: 60000 },
  );
  await page
    .locator('[data-action="play"]')
    .waitFor({ state: "visible", timeout: 120000 });
  observations.push({
    label: "environment",
    title: await page.title(),
    url: page.url(),
    browser: browser.version(),
    platform: os.platform(),
    release: os.release(),
    architecture: os.arch(),
    cpu: os.cpus()[0]?.model,
    totalMemory: os.totalmem(),
    viewport: { width: 1920, height: 1080 },
    headless: true,
  });
  await capture("welcome");
  await page.locator('[data-action="play"]').click();
  await page.waitForFunction(() => window.__leonida?.snapshot().simTime > 0, {
    timeout: 30000,
  });
  await snapshot("launched");
  if (mode === "outcomes") {
    await openCreative();
    await page.locator('[data-change="wanted"]').selectOption("1");
    await closePanel();
    await observeOutcome("arrest", 45000);
    await openCreative();
    await page.locator('[data-action="reset"]').click();
    await page.locator('[data-change="wanted"]').selectOption("1");
    await closePanel();
    await page.waitForTimeout(9000);
    await snapshot("escape-before-relocation");
    await page.keyboard.press("m");
    await page.locator('[data-action="teleport"][data-value="garage"]').click();
    await page.waitForTimeout(500);
    await snapshot("escape-map-teleport-garage");
    await capture("escape-garage");
    observations.push({
      label: "escape-method",
      value:
        "Normal map UI teleport to Sunset Customs; creative relocation, not continuous on-foot/driving evasion.",
    });
    await observeOutcome("escape", 45000);
  } else {
    await hold(["w"], 650);
    await snapshot("walked-forward");
    await page.keyboard.press("e");
    await page.waitForTimeout(600);
    await snapshot("entered-car");
    await capture("entered-car");
    await hold(["w"], 3800);
    await snapshot("drove-straight");
    await hold(["w", "d"], 2500);
    await hold(["w"], 3500);
    await snapshot("driving-impact-attempt");
    await capture("driving");
    await hold(["s", "Space"], 1400);
    await page.keyboard.press("g");
    await page.waitForTimeout(500);
    await snapshot("repaired");
    await hold(["s", "Space"], 600);
    await page.keyboard.press("e");
    await page.waitForTimeout(600);
    await snapshot("exited-car");
    await page.keyboard.press("Tab");
    await page.waitForTimeout(400);
    await snapshot("switched-character");
    await capture("on-foot");
    await openCreative();
    await page.locator("#spawn-kind").selectOption("sedan");
    await page.locator('#panel [data-action="spawn"]').click();
    await page.locator('#panel [data-action="prop"]').click();
    await page.locator('#panel [data-action="ped"]').click();
    if (checkpoint) {
      assertObservation(
        "civilian-density-default",
        (await page.locator('[data-change="peds"]').inputValue()) === "1",
        "Normal creative panel density remains 1",
      );
      await page.locator('[data-action="save"]').click();
      const before = await readUISave("civilian-save-before-wait");
      await closePanel();
      await capture("civilian-before");
      await page.waitForTimeout(3000);
      await capture("civilian-after");
      await openCreative();
      await page.locator('[data-action="save"]').click();
      const after = await readUISave("civilian-save-after-wait");
      const a = before.civilians?.[0], b = after.civilians?.[0];
      const moved = a && b ? Math.hypot(a.x - b.x, a.z - b.z) : 0;
      assertObservation("creative-civilian-moves", moved > 0.2, {
        savedCreativeCount: after.civilians?.length,
        displacementMetres: moved,
        density: after.settings.peds,
        visibilityRequiresScreenshotReview: true,
      });
    }
    await page.locator('[data-change="god"]').check();
    await page.locator('[data-change="wanted"]').selectOption("3");
    await capture("creative");
    await closePanel();
    await page.waitForTimeout(1000);
    await snapshot("creative-spawns-wanted-3");
    for (let second = 0; second < 30; second += 5) {
      await page.waitForTimeout(5000);
      await snapshot(`pursuit-wait-${second + 5}s`);
    }
    await capture("police-pursuit");
    await openCreative();
    await page.locator('[data-action="reset"]').click();
    await page.locator('[data-change="weather"]').selectOption("Rain");
    await page.locator('[data-action="save"]').click();
    const savedCheckpoint = checkpoint
      ? await readUISave("checkpoint-save-before-load")
      : null;
    if (checkpoint) {
      await page.locator('#panel [data-action="prop"]').click();
      await page.locator('#panel [data-action="ped"]').click();
      await snapshot("checkpoint-extra-entities-before-load");
    }
    await page.locator('[data-change="weather"]').selectOption("Clear");
    await page.locator('[data-action="load"]').click();
    if (checkpoint) {
      await page.locator('[data-action="save"]').click();
      const restored = await readUISave("checkpoint-save-after-load");
      const componentState = (save) => save.vehicles.map((v) => ({
        id: v.id, kind: v.kind, health: v.health, damage: v.damage,
      }));
      assertObservation(
        "checkpoint-vehicle-components-roundtrip",
        JSON.stringify(componentState(savedCheckpoint)) ===
          JSON.stringify(componentState(restored)),
        { ids: restored.vehicles.map((v) => v.id), scope: "Current normal-control save state; no injected damage" },
      );
      assertObservation(
        "checkpoint-custom-counts-roundtrip",
        savedCheckpoint.civilians.length === restored.civilians.length &&
          savedCheckpoint.props.length === restored.props.length,
        { before: { civilians: savedCheckpoint.civilians.length, props: savedCheckpoint.props.length },
          after: { civilians: restored.civilians.length, props: restored.props.length } },
      );
      assertObservation("checkpoint-weather-roundtrip", restored.weather === "Rain", restored.weather);
    }
    await closePanel();
    await page.waitForTimeout(1000);
    observations.push({
      label: "save-load-weather",
      displayedWeather: await page.locator("#weather").innerText(),
    });
    await snapshot("save-load-roundtrip");
    await capture("rain");
    await page.keyboard.press("m");
    await page.locator("#location-search").fill("Palmetto");
    const visibleLocations = await page
      .locator("#locations button:visible")
      .allTextContents();
    observations.push({
      label: "map-search",
      visibleLocations,
    });
    if (checkpoint) assertObservation(
      "map-search-filter",
      visibleLocations.length === 1 && visibleLocations[0].includes("Palmetto"),
      visibleLocations,
    );
    await capture("map");
    await closePanel();
    await page.keyboard.press("Escape");
    await page.waitForTimeout(300);
    const pauseStart = await snapshot("paused");
    await page.waitForTimeout(1500);
    const pauseEnd = await snapshot("pause-wait");
    observations.push({
      label: "pause-delta",
      simulationSeconds: pauseEnd.simTime - pauseStart.simTime,
    });
    await page.locator('[data-action="close"]').first().click();
  }
  const performanceReport = await page.evaluate(() => {
    const state = window.__leonida.snapshot();
    const sorted = [...state.frameTimes].sort((a, b) => a - b);
    const median = sorted[Math.floor(sorted.length / 2)];
    const tail = sorted.slice(Math.floor(sorted.length * 0.99));
    return {
      samples: sorted.length,
      medianFrameMs: median,
      medianFPS: 1000 / median,
      p99FrameMs: sorted[Math.floor(sorted.length * 0.99)],
      onePercentLowFPS: 1000 / (tail.reduce((a, b) => a + b, 0) / tail.length),
      maxFrameMs: sorted.at(-1),
      backend: state.backend,
      quality: state.quality,
      resolution: state.resolution,
      heap: performance.memory
        ? {
            used: performance.memory.usedJSHeapSize,
            total: performance.memory.totalJSHeapSize,
            limit: performance.memory.jsHeapSizeLimit,
          }
        : null,
    };
  });
  observations.push({
    label: "performance-short-session",
    ...performanceReport,
  });
} catch (error) {
  errors.push({ auditFailure: error.message, stack: error.stack });
  console.error(error);
  await capture("failure").catch(() => {});
} finally {
  await writeFile(
    `${output}/audit-results${suffix}.json`,
    JSON.stringify({ observations, errors, consoleMessages }, null, 2),
  );
  await context.close();
  await browser.close();
  console.log(
    JSON.stringify({
      artifact: `docs/evidence/audit-results${suffix}.json`,
      errorCount: errors.length,
      warningCount: consoleMessages.length,
    }),
  );
}
