import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import HavokPhysics from '@babylonjs/havok';
import { DirectionalLight, HavokPlugin, MeshBuilder, NullEngine, PhysicsAggregate, PhysicsEngineV2, PhysicsShapeType, Scene, ShadowGenerator, Vector3 } from '@babylonjs/core';
import { Player } from '../src/gameplay/Player';
import { Character } from '../src/gameplay/Character';
import { Combat } from '../src/gameplay/Combat';
import { DamageSystem } from '../src/gameplay/Damage';
import { VehicleSystem } from '../src/vehicles/VehicleSystem';
import type { Input } from '../src/core/Input';

test('seated handgun fire clears a lowered driver window, respects aim arcs and leaves steering available', async t => {
  const bytes = await readFile(new URL('../node_modules/@babylonjs/havok/lib/esm/HavokPhysics.wasm', import.meta.url));
  const h = await HavokPhysics({wasmBinary: bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer});
  const engine = new NullEngine(), scene = new Scene(engine); scene.enablePhysics(new Vector3(0, -9.81, 0), new HavokPlugin(false, h));
  const physics = scene.getPhysicsEngine() as PhysicsEngineV2, shadows = new ShadowGenerator(128, new DirectionalLight('sun', Vector3.Down(), scene));
  const ground = MeshBuilder.CreateBox('ground', {width: 60, height: 1, depth: 60}, scene); ground.position.y = -.5;
  const floor = new PhysicsAggregate(ground, PhysicsShapeType.BOX, {mass: 0}, scene);
  const input = {aim: false, mouseDown: false, dx: 0, dy: 0, down: () => false, axis: () => 0, take: () => false, takeFire: () => false} as unknown as Input;
  const player = new Player(scene, shadows, input, new Vector3(-2, .94, 0)), vehicles = new VehicleSystem({scene, shadows});
  const car = vehicles.spawn('sedan', new Vector3(0, 1, 0));
  const world = {spawn: Vector3.Zero(), roads: [], obstacles: [], locations: [], waterLevel: 0, update() {}, dispose() {}};
  const damage = new DamageSystem(scene, shadows, world, false);
  let hit = 0;
  const population = {pedestrians: [], officers: [], resist() {}, frighten() {}, witness: () => false, hurtPed: (_: unknown, n: number) => { hit += n; }};
  const combat = new Combat(scene, player, population as any, damage, vehicles, {crime() {}} as any);
  const step = (count: number) => { for (let n = 0; n < count; n++) { player.update(1 / 60); player.render(1 / 60); combat.update(1 / 60); vehicles.update(1 / 60); physics._step(1 / 60); } };
  t.after(() => {combat.dispose(); damage.dispose(); player.queries.dispose(); player.controller.dispose(); vehicles.dispose(); floor.dispose(); scene.dispose(); engine.dispose();});
  step(120); assert.ok(player.enter(car)); step(240); assert.equal(player.vehiclePhase, 'seated'); assert.equal(car.controlLocked, false);
  const door = car.model.doors.find(d => d.front && d.side === -1)!;
  const glass = car.model.windows.find(w => w.isDescendantOf(door.mesh))!, originalY = glass.position.y;
  Object.assign(input, {aim: true}); player.yaw = -Math.PI / 2; player.pitch = -.05;
  combat.select(0); step(160);
  assert.ok(glass.position.y < originalY - .15, 'actual glass slides into the door');
  assert.equal(combat.driveBy.ready, true, JSON.stringify({ wrist: player.model.jointPosition('leftHand').asArray(), muzzle: combat.held.muzzle().asArray(), vehicle: car.root.position.asArray(), ready: combat.driveBy.ready }));
  assert.ok(combat.held.muzzle().x < car.root.position.x - car.tuning.width / 2, 'physical muzzle is outside the window');
  const targetModel = new Character(scene, shadows, 'driveby-target');
  targetModel.root.position.copyFrom(car.root.position.add(new Vector3(-6, 0, 0))); targetModel.root.position.y = 0;
  targetModel.animate(1 / 60, 0);
  const ped = {model: targetModel};
  targetModel.parts.forEach(mesh => mesh.metadata = {...mesh.metadata, ped});
  (population.pedestrians as unknown[]).push(ped);
  player.camera.setTarget(targetModel.jointPosition('chest')); player.camera.getViewMatrix(true);
  combat.render(0);
  combat.fire(); assert.equal(combat.shots, 1); assert.ok(hit > 0, 'projectile reaches outside target instead of originating through the cabin');
  player.yaw = Math.PI / 2; step(120); combat.cooldown = 0; const ammo = combat.ammo; combat.fire(); assert.equal(combat.ammo, ammo, 'opposite-side cabin shot is blocked before spending ammunition');
  vehicles.control(car, {throttle: .5, steer: .3, brake: 0, handbrake: false, lift: 0}); assert.equal(car.input.steer, .3);
  Object.assign(input, {aim: false}); step(100); assert.ok(Math.abs(glass.position.y - originalY) < 1e-6, 'release closes the original intact window');
});
