import { chromium } from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=metal','--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1280,height:800}}),results=[],errors=[];
page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
async function capture(label){await page.waitForTimeout(1000);const state=await page.evaluate(()=>{const s=window.__leonida.game.scene;return {camera:{p:s.activeCamera.position.asArray(),target:s.activeCamera.getTarget().asArray(),view:s.activeCamera.getViewMatrix().asArray(),projection:s.activeCamera.getProjectionMatrix().asArray()},fog:s.fogEnabled,world:s.meshes.filter(m=>m.metadata?.worldDetail && (m.name.includes('compound-concrete')||m.name.includes('compound-olive')||m.name.includes('world/asphalt:global')||m.name.includes('COASTAL RESERVE'))).map(m=>({name:m.name,pos:m.position.asArray(),world:m.getWorldMatrix().asArray(),bounds:[m.getBoundingInfo().boundingBox.minimumWorld.asArray(),m.getBoundingInfo().boundingBox.maximumWorld.asArray()],active:s.getActiveMeshes().data.includes(m),ready:m.isReady(true),material:m.material?.id,imageSame:m.material?.imageProcessingConfiguration===s.imageProcessingConfiguration,sub:m.subMeshes.map(x=>({indexCount:x.indexCount,verticesCount:x.verticesCount,material:x.getMaterial()?.id,ready:x.effect?.isReady(),defines:x.materialDefines?.toString()}))})),streaming:window.__leonida.snapshot().streaming};});results.push({label,...state});await page.screenshot({path:`docs/evidence/diagnose-${label}-world.png`});console.log(label,JSON.stringify({camera:state.camera,world:state.world.map(m=>({name:m.name,ready:m.ready,active:m.active,imageSame:m.imageSame,bounds:m.bounds}))}));await writeFile('docs/evidence/diagnose-render-world.json',JSON.stringify({results,errors},null,2));}
try{await page.goto('http://127.0.0.1:4176/?backend=webgl&test');await page.locator('[data-action="play"]').waitFor({state:'visible',timeout:120000});await page.locator('[data-action="play"]').click();await page.keyboard.press('m');await page.locator('[data-action="teleport"][data-value="restricted-compound"]').click();await page.waitForFunction(()=>Math.abs(window.__leonida.snapshot().position[0]+449)<3&&!window.__leonida.snapshot().streamingBusy,{},{timeout:45000});await page.waitForTimeout(4500);await capture('base');
await page.evaluate(()=>{const s=window.__leonida.game.scene;s.fogEnabled=false;});await capture('no-fog');
await page.evaluate(()=>{const s=window.__leonida.game.scene;for(const m of s.materials)if(m.getClassName()==='PBRMaterial')m.imageProcessingConfiguration=s.imageProcessingConfiguration;});await capture('runtime-color');
await page.evaluate(()=>{const s=window.__leonida.game.scene;s.fogEnabled=true;for(const m of s.meshes)if(m.metadata?.worldDetail){m.unfreezeWorldMatrix();m.computeWorldMatrix(true);m.refreshBoundingInfo();}});await capture('unfreeze');
}finally{await browser.close();await writeFile('docs/evidence/diagnose-render-world.json',JSON.stringify({results,errors},null,2));}
