import { readFile,writeFile } from 'node:fs/promises';
import { projectMiami } from '../../../src/world/miami/projection';
const root=new URL('../../../data/world/miami/',import.meta.url);
const read=async(path:string)=>JSON.parse(await readFile(new URL(path,root),'utf8'));
const footprints=(await read('raw/county-buildings.geojson')).features,envelopes=(await read('building-envelopes.json')).features,addresses=(await read('raw/county-ubid.geojson')).features;
function bounds(geometry:any):number[]{
  const points:number[][]=[];function visit(c:any){if(typeof c[0]==='number')points.push(c);else c.forEach(visit);}visit(geometry.coordinates);
  return[Math.min(...points.map(p=>p[0])),Math.min(...points.map(p=>p[1])),Math.max(...points.map(p=>p[0])),Math.max(...points.map(p=>p[1]))];
}
function area(b:number[]){return Math.max(0,b[2]-b[0])*Math.max(0,b[3]-b[1]);}
function intersection(a:number[],b:number[]){return area([Math.max(a[0],b[0]),Math.max(a[1],b[1]),Math.min(a[2],b[2]),Math.min(a[3],b[3])]);}
function similarity(a:number[],b:number[]){const i=intersection(a,b);return i/(area(a)+area(b)-i||1);}
const rows=footprints.map((f:any)=>{
  const p=f.properties,b=bounds(f.geometry),mesh=p.UNIQUEID?envelopes.find((e:any)=>e.sourceUniqueId===p.UNIQUEID):null;
  const addressCandidates=p.UNIQUEID?addresses.filter((a:any)=>a.properties.UNIQUEID===p.UNIQUEID).map((a:any)=>({sourceId:`county-ubid:${a.properties.OBJECTID}`,address:a.properties.ADDRESS,floors:a.properties.FLOORS,geometryBboxSimilarity:similarity(b,bounds(a.geometry)),kind:similarity(b,bounds(a.geometry))>.9?'matching-footprint-association':'parcel-or-complex-association'})):[];
  const spatialCandidates=mesh?[]:envelopes.filter((e:any)=>intersection(b,e.bboxWgs84)/area(b)>.5).map((e:any)=>({id:e.id,footprintBboxFraction:intersection(b,e.bboxWgs84)/area(b)}));
  return{id:`county-buildings:${p.GlobalID}`,objectId:p.OBJECTID,uniqueId:p.UNIQUEID,year:p.YEARUPDATE,bboxWgs84:b,rawHeight:p.HEIGHT,mappedMeshId:mesh?.id??null,meshMatch:mesh?'exact-source-UNIQUEID-and-bounds':'unresolved',meshBboxSimilarity:mesh?similarity(b,mesh.bboxWgs84):null,addresses:addressCandidates,spatialCandidates,status:mesh?'source-2015-mesh':'newer-footprint-without-unique-id',gaps:[...(mesh?['Source mesh dates to2015; footprint is not proof of unchanged contemporary facade.']:['2023 footprint part has no UNIQUEID and no documented HEIGHT; preserve it in map index without inventing surveyed height.','Bounding-box candidates are review hints only, not automatic building identity or proof of polygon coverage.']),...(addressCandidates.some((a:any)=>a.kind==='parcel-or-complex-association')?['UBID address/floor count spans a parcel or multiple buildings; do not apply representative address or whole-tower height to every part.']:[])]};
});
const exact=rows.filter((r:any)=>r.mappedMeshId),linked=new Set(exact.map((r:any)=>r.mappedMeshId));
const report={version:1,policy:'Exact UNIQUEID joins require matching source bounds. Administrative UBID complex records and approximate spatial candidates remain separate from physical building identity. No geometry is moved or discarded.',counts:{footprintFeatures:rows.length,polygonParts:footprints.reduce((n:number,f:any)=>n+(f.geometry.type==='Polygon'?1:f.geometry.coordinates.length),0),exactI3sMatches:exact.length,unresolvedNewerFootprints:rows.length-exact.length,i3sMeshes:envelopes.length,i3sWithoutExactCurrentFootprint:envelopes.length-linked.size},minimumExactBboxSimilarity:Math.min(...exact.map((r:any)=>r.meshBboxSimilarity)),rows,i3sWithoutExactCurrentFootprint:envelopes.filter((e:any)=>!linked.has(e.id)).map((e:any)=>({id:e.id,uniqueId:e.sourceUniqueId,year:e.yearUpdated,bboxWgs84:e.bboxWgs84,gap:'Source2015mesh has no exact UNIQUEID join to current County footprints. Check replacement/demolition/new footprint parts before treating as contemporary.'}))};
if(report.minimumExactBboxSimilarity<.95)throw new Error('Unexpected source-ID geometry mismatch');
await writeFile(new URL('building-reconciliation.json',root),JSON.stringify(report,null,2)+'\n');
const intersectionWgs84=[-80.1907224560056,25.7661748271726];
await writeFile(new URL('coverage-plan.json',root),JSON.stringify({version:1,initial:{id:'brickell-core-r1',bboxWgs84:[-80.199,25.7596,-80.187,25.7704],streetIntersection:{name:'SE8thStreet / BrickellAvenue',source:'city-streets',segmentIds:[11901,10802,14789,10801],wgs84:intersectionWgs84,position:projectMiami(intersectionWgs84[0],intersectionWgs84[1])}},masterBoundary:{path:'raw/city-boundary.geojson',type:'Official administrative City of Miami boundary; includes water, not a land mask'},next:[{id:'brickell-south',purpose:'Continue actual Brickell Avenue to SE15thRoad, thenRickenbacker approach; join existing south edge.'},{id:'downtown-north',purpose:'MiamiRiver crossings and Downtown; bridge deck and opening-state authoring required.'},{id:'brickell-key-east',purpose:'Entire BrickellKey and actual connecting causeway; preserve shoreline and separate deck elevations.'},{id:'brickell-west',purpose:'WestBrickell throughMetrorail/SW2ndAve; retain grade-separated transit and I95 geometry.'}],expansionPolicy:'Use shared fixed ENU origin and contiguous1200m tiles; fetch all intersecting source IDs with halo, retain full source features and deduplicate byGlobalID/sourceObjectId. Never scale distances to fit. Reconcile overlap/replacement before rendering mixed-age buildings.',remaining:['2015mesh vs2023footprint coverage','Primary facade/art and current building identity review','Bridge decks and vertical road geometry','Curbs, lane and sidewalk widths per approved/as-built source','Street furniture, signs, vegetation and surface condition inventories','City-wide coverage outside firstAOI']},null,2)+'\n');
console.log(report.counts,report.minimumExactBboxSimilarity);
