import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {ecef,rootUrl,safeError,safeUrl,validateConfiguration} from '../src/access';
test('remote sessions require locally entered credentials and valid ion assets',()=>{assert.throws(()=>validateConfiguration('google','','','normal'),/own valid/);assert.throws(()=>validateConfiguration('ion','test-token','0','normal'),/positive/);assert.throws(()=>validateConfiguration('other','','','normal'),/supported/);assert.throws(()=>validateConfiguration('fixture','','','other'),/fixture case/);assert.equal(validateConfiguration('fixture','discard-me','','normal').credential,'');assert.equal(rootUrl(validateConfiguration('google','test-only','','normal')),'https://tile.googleapis.com/v1/3dtiles/root.json');assert.equal(rootUrl(validateConfiguration('ion','test-only','2275207','normal')),'');});
test('diagnostics remove credentials and session query parameters',()=>{const key='unit-test-credential';const output=safeError(new Error(`HTTP403 https://tile.googleapis.com/v1/root.json?key=${key}&session=hidden Bearer hidden-token access_token=other ${key}`),key);assert.ok(!output.includes(key));assert.ok(!output.includes('hidden-token'));assert.ok(!output.includes('session=hidden'));assert.ok(!output.includes('access_token=other'));assert.equal(safeUrl('https://api.cesium.com/v1/assets/1/endpoint?access_token=secret#hidden'),'api.cesium.com/v1/assets/1/endpoint');});
test('WGS84 ECEF helper retains real metre scale',()=>{assert.deepEqual(ecef(0,0),[6378137,0,0]);assert.ok(Math.abs(ecef(90,0)[2]-6356752.314245179)<1e-6);assert.ok(Math.abs(ecef(0,0,100)[0]-ecef(0,0)[0]-100)<1e-9);});
test('synthetic test tiles carry separate source credits and valid buffers',async()=>{const tiles=JSON.parse(await readFile(new URL('../public/fixture/tileset.json',import.meta.url),'utf8'));assert.equal(tiles.root.children.length,2);assert.equal(tiles.root.transform.length,16);const credits=[];for(const name of ['a','b']){const b=await readFile(new URL(`../public/fixture/${name}.glb`,import.meta.url));assert.equal(b.readUInt32LE(0),0x46546c67);assert.equal(b.readUInt32LE(8),b.length);const size=b.readUInt32LE(12),doc=JSON.parse(b.subarray(20,20+size).toString());credits.push(doc.asset.copyright);assert.equal(doc.accessors[0].count,24);assert.equal(doc.accessors[2].count,36);assert.match(doc.asset.generator,/not Miami/);}assert.equal(new Set(credits).size,2);});
test('preview source does not persist or preconfigure provider credentials',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),code=await readFile(new URL('../src/main.ts',import.meta.url),'utf8');assert.match(html,/id="credential" type="password" autocomplete="off"/);assert.ok(!code.includes('localStorage'));assert.ok(!code.includes('sessionStorage'));assert.ok(!code.includes('VITE_ION'));assert.match(code,/getAttributions\(\)/);assert.ok(!code.includes('attributions[0]'));assert.match(code,/function disconnect/);});

test('browser-restricted API keys retain only the page origin cross-origin',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),code=await readFile(new URL('../src/main.ts',import.meta.url),'utf8');assert.match(html,/name="referrer" content="strict-origin-when-cross-origin"/);assert.match(code,/referrerPolicy:'strict-origin-when-cross-origin'/);});

test('default waits for user ion access without auto-connecting fixtures or APIs',async()=>{const html=await readFile(new URL('../index.html',import.meta.url),'utf8'),code=await readFile(new URL('../src/main.ts',import.meta.url),'utf8');assert.match(html,/<option value="ion" selected>/);assert.match(html,/<div id="fixture-badge" hidden>/);assert.ok(!code.includes("connect(validateConfiguration('fixture'"));assert.match(code,/state.textContent='Waiting for access token'/);});
