import {writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
// An independent double-precision column-matrix oracle; no Babylon math.
const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
const mul=(a,b)=>Array.from({length:16},(_,i)=>{let n=0;const r=i%4,c=Math.floor(i/4);for(let k=0;k<4;k++)n+=a[k*4+r]*b[c*4+k];return n;});
const point=(m,p)=>[0,1,2].map(r=>m[r]*p[0]+m[4+r]*p[1]+m[8+r]*p[2]+m[12+r]);
const axis=(a,degrees)=>{const v=[0,0,0,Math.cos(degrees*Math.PI/360)];v[a]=Math.sin(degrees*Math.PI/360);return v;};
const trs=(t=[0,0,0],q=[0,0,0,1],s=[1,1,1])=>{const [x,y,z,w]=q;return [(1-2*(y*y+z*z))*s[0],2*(x*y+z*w)*s[0],2*(x*z-y*w)*s[0],0,2*(x*y-z*w)*s[1],(1-2*(x*x+z*z))*s[1],2*(y*z+x*w)*s[1],0,2*(x*z+y*w)*s[2],2*(y*z-x*w)*s[2],(1-2*(x*x+y*y))*s[2],0,...t,1];};
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],sub=(a,b)=>a.map((x,i)=>x-b[i]);
function tetra(points){const positions=[],normals=[],indices=[],center=[0,1,2].map(i=>points.reduce((s,p)=>s+p[i],0)/4);for(let face of [[0,1,2],[0,3,1],[0,2,3],[1,3,2]]){let [a,b,c]=face.map(i=>points[i]),n=cross(sub(b,a),sub(c,a));if(n.reduce((s,x,i)=>s+x*(center[i]-a[i]),0)>0)[b,c]=[c,b];n=cross(sub(b,a),sub(c,a));const l=Math.hypot(...n),start=positions.length/3;for(const p of [a,b,c]){positions.push(...p.map(Math.fround));normals.push(...n.map(x=>Math.fround(x/l)));}indices.push(start,start+1,start+2);}return{positions,normals,indices};}
const body=tetra([[0,0,0],[1.4,.1,0],[.15,1.1,.2],[.1,.15,-.7]]),marker=tetra([[0,0,0],[.05,0,0],[0,.03,0],[0,0,-.04]]);
const gltf={asset:{version:'2.0',generator:'Original independently authored tile-frame fixture',extras:{provenance:'Original synthetic geometry and transforms; no geographic/provider data.',units:'metres'}},scene:0,scenes:[{nodes:[0,4,5,6,7]}],nodes:[{name:'nonuniform-parent',translation:[.35,.2,-.6],rotation:axis(1,31),scale:[1.3,.9,.7],children:[1,2]},{name:'asymmetric-body',mesh:0,translation:[.6,.1,.2],rotation:axis(2,17)},{name:'nested-elbow',translation:[-.6,.7,.3],rotation:axis(0,-23),children:[3]},{name:'offset-nose',mesh:1,translation:[.2,.4,-.25],rotation:axis(2,11),scale:[.45,.8,1.2]},...[[0,0,0],[1,0,0],[0,1,0],[0,0,-1]].map((p,i)=>({name:['marker-origin','marker-east','marker-up','marker-north'][i],mesh:2+i,translation:p}))],meshes:[],materials:[],buffers:[{byteLength:0}],bufferViews:[],accessors:[]};
const buffers=[];let offset=0;const meshGeometry=[body,body,marker,marker,marker,marker];
function accessor(values,components,index=false){const b=Buffer.alloc(values.length*(index?2:4));values.forEach((v,i)=>index?b.writeUInt16LE(v,i*2):b.writeFloatLE(v,i*4));const padded=Buffer.alloc(Math.ceil(b.length/4)*4);b.copy(padded);buffers.push(padded);const view=gltf.bufferViews.length;gltf.bufferViews.push({buffer:0,byteOffset:offset,byteLength:b.length,target:index?34963:34962});offset+=padded.length;const a={bufferView:view,componentType:index?5123:5126,count:values.length/components,type:components===1?'SCALAR':'VEC3'};if(!index){a.min=[0,1,2].map(c=>Math.min(...values.filter((_,i)=>i%3===c)));a.max=[0,1,2].map(c=>Math.max(...values.filter((_,i)=>i%3===c)));}gltf.accessors.push(a);return gltf.accessors.length-1;}
for(let i=0;i<meshGeometry.length;i++){const g=meshGeometry[i];gltf.materials.push({name:['body-blue','nose-orange','origin-black','east-red','up-green','north-blue'][i],pbrMetallicRoughness:{baseColorFactor:[[.15,.35,.8,1],[1,.3,.05,1],[.1,.1,.1,1],[1,0,0,1],[0,1,0,1],[0,.1,1,1]][i],metallicFactor:0,roughnessFactor:.8},doubleSided:false});gltf.meshes.push({primitives:[{attributes:{POSITION:accessor(g.positions,3),NORMAL:accessor(g.normals,3)},indices:accessor(g.indices,1,true),material:i,mode:4}]});}
gltf.buffers[0].byteLength=offset;const binary=Buffer.concat(buffers),json=Buffer.from(JSON.stringify(gltf)),jsonPadded=Buffer.alloc(Math.ceil(json.length/4)*4,32);json.copy(jsonPadded);const glb=Buffer.alloc(12+8+jsonPadded.length+8+binary.length);glb.writeUInt32LE(0x46546c67);glb.writeUInt32LE(2,4);glb.writeUInt32LE(glb.length,8);glb.writeUInt32LE(jsonPadded.length,12);glb.writeUInt32LE(0x4e4f534a,16);jsonPadded.copy(glb,20);const bin=20+jsonPadded.length;glb.writeUInt32LE(binary.length,bin);glb.writeUInt32LE(0x004e4942,bin+4);binary.copy(glb,bin+8);
const up=trs(undefined,axis(0,90)),tileParent=trs([17,-9,4],axis(2,27)),tileChild=trs([-3,2,1.25],axis(2,-16)),frame=trs([28,3,-14],axis(0,-90));
const combined=mul(frame,mul(tileParent,mul(tileChild,up))),parentByNode=new Map();gltf.nodes.forEach((n,i)=>n.children?.forEach(c=>parentByNode.set(c,i)));
const nodeWorld=i=>{const n=gltf.nodes[i],m=trs(n.translation,n.rotation,n.scale);return parentByNode.has(i)?mul(nodeWorld(parentByNode.get(i)),m):m;};
const records=gltf.nodes.flatMap((n,i)=>{if(n.mesh===undefined)return[];const g=meshGeometry[n.mesh],node=nodeWorld(i),vertices=Array.from({length:g.positions.length/3},(_,v)=>g.positions.slice(v*3,v*3+3)),local=vertices.map(p=>point(node,p));return[{name:n.name,mesh:n.mesh,sourcePositions:g.positions,sourceIndices:g.indices,sourceNormals:g.normals,nodeWorld:node,gltfWorld:local,rhWorld:local.map(p=>point(combined,p)),lhWorld:local.map(p=>{const v=point(combined,p);return[v[0],v[1],-v[2]];})}];});
const all=records.flatMap(r=>r.gltfWorld),tilePoints=all.map(p=>point(up,p));function box(points){const min=[0,1,2].map(i=>Math.min(...points.map(p=>p[i]))),max=[0,1,2].map(i=>Math.max(...points.map(p=>p[i]))),c=min.map((x,i)=>(x+max[i])/2),h=min.map((x,i)=>(max[i]-x)/2);return[...c,h[0],0,0,0,h[1],0,0,0,h[2]];}
const childBox=box(tilePoints),childCorners=Array.from({length:8},(_,i)=>[childBox[0]+(i&1?1:-1)*childBox[3],childBox[1]+(i&2?1:-1)*childBox[7],childBox[2]+(i&4?1:-1)*childBox[11]]);
const tileset={asset:{version:'1.1',gltfUpAxis:'Y'},geometricError:4,root:{transform:tileParent,boundingVolume:{box:box(childCorners.map(p=>point(tileChild,p)))},geometricError:2,refine:'REPLACE',children:[{transform:tileChild,boundingVolume:{box:childBox},geometricError:0,content:{uri:'asymmetric.glb'}}]}};
await writeFile(new URL('../fixtures/asymmetric.glb',import.meta.url),glb);await writeFile(new URL('../fixtures/tileset.json',import.meta.url),JSON.stringify(tileset,null,2)+'\n');await writeFile(new URL('../fixtures/expected.json',import.meta.url),JSON.stringify({version:1,units:'metres',provenance:'Original synthetic nongeographic fixture. Oracle uses independent column-matrix arithmetic.',glbSha256:createHash('sha256').update(glb).digest('hex'),up,tileParent,tileChild,frame,combined,records},null,2)+'\n');console.log(JSON.stringify({bytes:glb.length,meshes:records.length,vertices:records.reduce((n,r)=>n+r.rhWorld.length,0),triangles:records.reduce((n,r)=>n+r.sourceIndices.length/3,0),sha256:createHash('sha256').update(glb).digest('hex')}));
