import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createPublicCollisionQueries} from '../src/PublicCollisionQueries';
import {buildMiamiLaneGraph} from '../vendor/world/miami/MiamiRoads';
import {insideMiamiPolygon} from '../vendor/world/miami/MiamiQueries';
import type {MiamiDataset,MiamiPolygon} from '../vendor/world/miami/types';
const root=new URL('../',import.meta.url),output=new URL('output/',root),json=async(name:string)=>JSON.parse(await readFile(new URL(name,root),'utf8'));
const [manifest,dataset,source,config,input]=await Promise.all(['output/packages.json','output/dataset.json','data/i3s-geographic.json','output/runtime-query.json','data/dataset-r5.json'].map(json));
const h=await readFile(new URL('terrain/heights.f32',output)),m=await readFile(new URL('terrain/source-mask.u8',output));
const queries=createPublicCollisionQueries(config,new Float32Array(h.buffer.slice(h.byteOffset,h.byteOffset+h.byteLength)),m);
const area=(polygon:MiamiPolygon)=>polygon.reduce((total,ring,index)=>total+(index?-1:1)*Math.abs(ring.reduce((a,p,i)=>{const q=ring[(i+1)%ring.length];return a+p[0]*q[1]-q[0]*p[1];},0)/2),0);
const dry=dataset.land.flatMap((l:any)=>l.polygons) as MiamiPolygon[],wet=dataset.water.flatMap((l:any)=>l.polygons) as MiamiPolygon[];
const lanes=buildMiamiLaneGraph(dataset.roads,{bounds:dataset.bounds,heightAt:(x,z)=>queries.floorHeightAt(x,z)??NaN,dryCoverage:{polygons:dry,sourceIds:[],confidence:'mapped',gaps:[]},pruneDeadEnds:false});
const graph=lanes.map(()=>new Set<number>());for(const node of lanes)for(const next of node.next){graph[node.id].add(next);graph[next].add(node.id);}
const visited=new Set<number>(),components:number[][]=[];for(const node of lanes){if(visited.has(node.id))continue;const members:number[]=[],pending=[node.id];visited.add(node.id);while(pending.length){const id=pending.pop()!;members.push(id);for(const next of graph[id])if(!visited.has(next)){visited.add(next);pending.push(next);}}components.push(members);}components.sort((a,b)=>b.length-a.length);
const dist=(x:number,z:number,b:any)=>Math.hypot(Math.max(b.minX-x,0,x-b.maxX),Math.max(b.minZ-z,0,z-b.maxZ));
const budgetSamples=[];for(let x=dataset.bounds.minX+20;x<dataset.bounds.maxX-20;x+=75)for(let z=dataset.bounds.minZ+20;z<dataset.bounds.maxZ-20;z+=75){if(!queries.hasSourceGround(x,z))continue;budgetSamples.push({x,z,collisionBytes:manifest.chunks.filter((c:any)=>dist(x,z,c.bounds)<210).reduce((n:number,c:any)=>n+c.bytes,0),preloadBytes:manifest.chunks.filter((c:any)=>dist(x,z,c.bounds)<420).reduce((n:number,c:any)=>n+c.bytes,0)});}
const missingGroups=source.buildings.filter((b:any)=>!dataset.buildings.some((f:any)=>f.mappedMeshId===b.id)).map((b:any)=>({id:b.id,sourceUniqueId:b.sourceUniqueId,bboxWgs84:b.bboxWgs84,note:'3D collider retained, no joined County footprint part'}));
let roadM=0;for(const road of dataset.roads)for(let i=1;i<road.centerline.length;i++){const a=road.centerline[i-1],b=road.centerline[i];roadM+=Math.hypot(a[0]-b[0],a[2]-b[2]);}
const report={worldId:manifest.worldId,sourceBboxWgs84:source.bboxWgs84,physicalSurfaceBboxWgs84:manifest.coverage.sourceBboxWgs84,bounds:dataset.bounds,areaSquareMetres:{bounds:(dataset.bounds.maxX-dataset.bounds.minX)*(dataset.bounds.maxZ-dataset.bounds.minZ),dry:dry.reduce((a,p)=>a+area(p),0),mappedWater:wet.reduce((a,p)=>a+area(p),0),dryComponents:dry.map(p=>area(p)).sort((a,b)=>b-a)},buildingCount:source.buildings.length,buildingVertices:source.buildings.reduce((n:number,b:any)=>n+b.vertices,0),buildingsWithoutJoinedFootprint:missingGroups,countyFootprintParts:{retainedInput:input.buildings.length,joinedOutput:dataset.buildings.length,unjoinedInput:input.buildings.filter((b:any)=>!b.mappedMeshId).length},roads:{count:dataset.roads.length,centerlineM:roadM,names:[...new Set(dataset.roads.map((r:any)=>r.name))].sort(),excluded:manifest.exclusions.roads},navigation:{laneNodes:lanes.length,terminalNodes:lanes.filter(n=>!n.next.length).length,weakComponentNodeCounts:components.map(c=>c.length),largestComponentCoverage:components[0].length/lanes.length,invalidHeights:lanes.filter(n=>!Number.isFinite(n.y)).length},terrain:{sourcePixels:h.byteLength/4,olderFallbackPixels:[...m].filter(n=>n===1).length},residency:{sampleSpacingM:75,sampledDryPoints:budgetSamples.length,byteBudget:96*1024*1024,maxCollision:budgetSamples.reduce((a,b)=>b.collisionBytes>a.collisionBytes?b:a),maxPreload:budgetSamples.reduce((a,b)=>b.preloadBytes>a.preloadBytes?b:a),note:'Chunk bytes only, excludes JS/physics/GPU duplication; active-body anchors can increase requirements.'},dataHashes:await Promise.all(['data/i3s-geographic.bin','data/i3s-geographic.json','data/preparation.json','output/packages.json','output/dataset.json'].map(async path=>({path,sha256:createHash('sha256').update(await readFile(new URL(path,root))).digest('hex')})))};
await writeFile(new URL('expansion-audit.json',output),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,buildingsWithoutJoinedFootprint:missingGroups.length},null,2));
